#!/usr/bin/env ruby
require 'changelog/cli'
require 'changelog/helper'

begin
    Changelog::CLI.start
rescue Changelog::Helper::Abort => ex
    $stderr.puts ex.message
    exit 1
rescue Changelog::Helper::Done
    exit
end


