#!/usr/bin/env ruby
require 'changelog/cli'
require 'changelog/helper'
require 'colorize'

begin
    Changelog::CLI.start
rescue Changelog::Helper::Abort => ex
    $stderr.puts ex.message
    exit 1
rescue Changelog::Helper::Done
    exit
rescue Interrupt
    $stderr.puts "\nAbort mission! I repeat! Abort mission!".red
    exit 1
end


